name = "BoatDynamics"
uuid = "5db923ff-3993-4487-8aba-e08b6a0966e3"
authors = ["Grzegorz Orzechowski <2590699+gorzech@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Revise = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
